create table if not exists public.assist_members (
  discord_user_id text primary key,
  display_name text not null default 'Miembro',
  username text not null default 'usuario',
  avatar_url text not null default '',
  assist_points integer not null default 0 check (assist_points >= 0),
  role_name text not null default 'Miembro de la Bóveda',
  last_assist_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.assist_events (
  id bigint generated by default as identity primary key,
  external_event_id text unique,
  helper_id text not null references public.assist_members(discord_user_id) on delete cascade,
  helper_name text not null default 'Miembro',
  giver_id text,
  giver_name text not null default 'Otro miembro',
  reason text not null default 'community_help' check (reason in ('gifted_sprite', 'index_help', 'safe_exchange', 'community_help')),
  created_at timestamptz not null default now()
);

create index if not exists assist_members_points_idx on public.assist_members (assist_points desc);
create index if not exists assist_events_created_idx on public.assist_events (created_at desc);
create index if not exists assist_events_helper_idx on public.assist_events (helper_id);

alter table public.assist_members enable row level security;
alter table public.assist_events enable row level security;

drop policy if exists "Public can read assist members" on public.assist_members;
create policy "Public can read assist members"
on public.assist_members for select
to anon, authenticated
using (true);

drop policy if exists "Public can read assist events" on public.assist_events;
create policy "Public can read assist events"
on public.assist_events for select
to anon, authenticated
using (true);

-- No public insert, update or delete policies are created.
-- Only the Edge Function using the service role can write.
